"""Add signal unit to IO points

Revision ID: 66d1634b270f
Revises: 0824aa3bd9f6
Create Date: 2026-09-22 20:22:39.520166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d1634b270f'
down_revision = '0824aa3bd9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('io_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('io_points', schema=None) as batch_op:
        batch_op.drop_column('signal_unit')

    # ### end Alembic commands ###
